#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Sbarbat\Chip\Command\Game;

$game = new Game();
$app = new Application();
$app->add($game);
$app->setDefaultCommand($game->getName());

$app->run();